### ISSUE TITLE
ModuleNotFoundError after Anaconda install

### ISSUE THREAD

**Issue by ludwa6** [pandas-profiling/pandas-profiling#136]
Running Python 3.6 in Jupyterlab 0.32.1, Anaconda Navigator tells me that it has installed pandas-profiling , Version 1.4.1... But then following instructions in this README, initializing my new notebook with the following:  

import pandas as pd
import pandas_profiling

... i get this ModuleNotFoundError : No module named 'pandas_profiling'.  

Am running pandas version 0.23.0, if that matters.

**Comment by vinhdang-tsocial** [comment]
I have the same problem here. Jupyter cannot find the package.

**Comment by vpolimenov** [comment]
There is actually PR updating the ReadMe as well: https://github.com/pandas-profiling/pandas-profiling/pull/123

**Comment by JosPolfliet** [comment]
Merged #123

**Comment by nateGeorge** [comment]
This still seems to be an issue.  What I've found is it may depend on which other packages you have installed.  My solution was to specify the version of pandas-profiling when doing a conda install:

`conda install -c conda-forge pandas-profiling=2.6.0`

Substitute '2.6.0' with the latest version here: https://anaconda.org/conda-forge/pandas-profiling

When I didn't specify the version, it seemed to install an older version (1.4.1-0 for Linux).  When I did specify the most recent version, it also downloaded qt-5.9.7 which it hadn't done before.  I'm not sure what's going on, because in another conda env, I was able to simply do `conda install -c conda-forge pandas-profiling` and it worked, but I had installed some other packages first.

**Comment by raybg** [comment]
Hi,

pandas_profiling is working in jupyter notebook and in the VS Code when its run from Anaconda Navigator. 
**but it is not running from my newly installed VS Code user setup file. 

Steps Tried
Conda Install - Checked
pip install - Checked
Ana. Nav. Environment Install - Checked

FYI: I am non-technical person. so need a bit detailed resolution.

**Comment by sbrugman** [comment]
> Hi,
> 
> pandas_profiling is working in jupyter notebook and in the VS Code when its run from Anaconda Navigator.
> **but it is not running from my newly installed VS Code user setup file.
> 
> Steps Tried
> Conda Install - Checked
> pip install - Checked
> Ana. Nav. Environment Install - Checked
> 
> FYI: I am non-technical person. so need a bit detailed resolution.

This is most likely not an issue with the software, but a request for help in how to use `pandas-profiling`. Please consider asking your question on stackoverflow. There is a specific tag for `pandas-profiling`:

https://stackoverflow.com/questions/tagged/pandas-profiling
