### ISSUE TITLE
Do methods exist to access results of pandas_profiling which are used in HTML result?

### ISSUE THREAD

**Issue by vlstrode** [pandas-profiling/pandas-profiling#145]
Looking to review and interrogate the results of the pandas_profiling through additional python code.  To do this, would need methods inside package which would expose those results.

Example:
```
profile(df.[column name(s)]).distinct_count()
profile(df.[column name(s)]).distinct_values()
profile(df.[column name(s)]).pct_missing()
etc...
```

**Comment by Aylr** [comment]
I like the direction you are going here. Something like an API as an alternative use rather than only creating an html ProfileReport. However, I do wonder why not just use pandas functions like `df['column'].value_counts()` and `df['column'].unique()` and something like `df['column'].isna().sum() / len(df)`. Granted that last one isn't nearly as pretty as the one you suggest!
