### ISSUE TITLE
Change Requests

### ISSUE THREAD

**Issue by sqlquery** [pandas-profiling/pandas-profiling#35]
Hi Jos,

As previously sent, here is the list of things I think would make this profiling tool even better.

pandas_profiling: 

-     In dataset info area of the report, add filename and file size
-     at the bottom of the report, add a simple output grid/table listing of the variables in the order they came, and their variable type. Something like df.dtypes 
-     for categorical/text data, add min/max/average length of the strings (this is helpful for people who will build database tables on the data) 
-     not sure how you'd do it, but it'd be good to know how many records are exact duplicates of one another, counts and % 
-     for categorical/text data, it'd be great to illustrate the regex expression for strings, an example would be which have number data in strings - e.g. phone number regex expression is like ((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}  this regex thing is clearly likely much more difficult, just figured I’d throw it out there…

**Comment by conradoqg** [comment]
Hey,

I implemented part of your suggestions, here is my comment for each one:

> In dataset info area of the report, add filename and file size

As far as I know, pandas doesn't store the data source filename and file size, so I think it is not possible.

> at the bottom of the report, add a simple output grid/table listing of the variables in the order they came, and their variable type. Something like df.dtypes 

OK.

> for categorical/text data, add min/max/average length of the strings (this is helpful for people who will build database tables on the data) 

OK.

> not sure how you'd do it, but it'd be good to know how many records are exact duplicates of one another, counts and % 

The report already have the count of duplicated rows, but to make it clear I'm adding that to the head of the report (always showing that information, not only when there are duplicates)

> for categorical/text data, it'd be great to illustrate the regex expression for strings, an example would be which have number data in strings - e.g. phone number regex expression is like ((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}  this regex thing is clearly likely much more difficult, just figured I’d throw it out there… 

I think this will be very complex since it's hard to agree for general regexes to identify known information like phone number, addresses, governmental ids, and etc. I think we shouldn't do that.

After the authors merge the PR #83 I'll submit a new one that implements those suggestions.

Best

**Comment by sqlquery** [comment]
Thank you all, I'm looking forward to trying all this out...Rich
