### ISSUE TITLE
Data have rejected variables, but do not display in Warnings

### ISSUE THREAD

**Issue by NickYi1990** [pandas-profiling/pandas-profiling#389]
**Data have rejected variables, but do not display in Warnings**

```python
from pandas_profiling import ProfileReport
profile = ProfileReport(pd.DataFrame({"a": [1,1,1,1,1,1]}), minimal=True)
```
![image](https://user-images.githubusercontent.com/13381684/75269098-56240900-5833-11ea-8774-b588d3ec874c.png)

**2.5.0**

**Comment by sbrugman** [comment]
Thank you for reporting this. We invite interested contributors to create a pull request with this functionality. More details can be found in the [contribution guide](https://github.com/pandas-profiling/pandas-profiling/blob/master/CONTRIBUTING.md).

**Comment by loopyme** [comment]
I noticed that four types of warning messages(`Uniform`,`Unique`,`Rejected`,`Constant`) are ignored when rendering. Since `Rejected` is always comes with other warnings, is it necessary to add all types of warnings above?

or it will end up like this:
![Screenshot-20200413140323-1283x574](https://user-images.githubusercontent.com/33747091/79096552-19cf4c80-7d90-11ea-9693-068790bab0c2.png)

**Comment by sbrugman** [comment]
v2.7.0 changes the behavior to report all warnings, except "rejected", as that would be redundant.
