### ISSUE TITLE
Duplicate (and highly correlated) categoricals

### ISSUE THREAD

**Issue by dpavlic** [pandas-profiling/pandas-profiling#40]
Duplicated categorical variables are not flagged:

![categorical_dupes](https://cloud.githubusercontent.com/assets/1075079/22222761/10a4c292-e186-11e6-8d84-294326cb20cd.png)

Perhaps it would be worthwhile to detect these types of exact duplicates, or maybe also perform a correlation analysis on categoricals?

**Comment by tejaslodaya** [comment]
Yes, this has not been taken care of, because code uses `df.corr()` which is only applicable for numerical variables. For correlation of categorical variables, one should use Cramer's V.

Helper function -

```
def get_vartype(data):
    distinct_count=data.nunique(dropna=False)
    leng=len(data)
    if distinct_count <=1:
        return 'CONST'
    elif com.is_numeric_dtype(data):
        return 'NUM'
    elif com.is_datetime64_dtype(data):
        return 'DATE'
    elif distinct_count==leng:
        return 'UNIQUE'
    else:
        return 'CAT'
```

`import scipy.stats as stats`

```
def cramers_corrected_stat(confusion_matrix):
    chi2 = stats.chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    phi2 = chi2/n
    r,k = confusion_matrix.shape
    phi2corr = max(0, phi2 - ((k-1)*(r-1))/(n-1))
    rcorr = r - ((r-1)**2)/(n-1)
    kcorr = k - ((k-1)**2)/(n-1)
    return np.sqrt(phi2corr / min( (kcorr-1), (rcorr-1)))
```

Final call : 
```
for col1,s1 in df.iteritems():
    if get_vartype(s1)!='CAT':
        continue
    for col2,s2 in df.iteritems():

        if col1==col2:
            continue
        if get_vartype(s2)!='CAT':
            continue
        confusion_matrix=pd.crosstab(s1,s2)
        cramers_corr=cramers_corrected_stat(confusion_matrix)
        if(cramers_corr>0.9):
            print(cramers_corr,'\t',col1,'\t',col2)
```

CC: @dpavlic @JosPolfliet

**Comment by JosPolfliet** [comment]
I implemented a draft for this, but in testing find that the Cramer's V is not specific enough to decide to reject a variable.
Example: a frequency matrix X/Y like this
```
X               Relict  Valid
Y 
Relict H                    1      0
Relict OC                  65      0
Relict iron                 1      0
Stone-uncl                  0     50
Stone-ung                   0      1
Ureilite-pmict              0     23
```

would lead to a Cramer's V of 1. I think there is no one variable better than the other, it is up to the analyst to investigate and decide if the increase in degrees of freedom (from modelling only Y vs only X) is worth the information that is contained. I do agree that it should be printed since it is something you want to know before modelling. 

Maybe just having an alert that these categorical variables are 'hierarchical' will do for now?

**Comment by JosPolfliet** [comment]
On the other hand side, something like this
```
d=pd.DataFrame(index=range(1,8))
d['a'] = ['chien', 'chien', 'chien', 'chien', 'chat','chat','chat']
d['b'] = ['dog', 'dog', 'dog', 'dog', 'cat','cat','cat']
ct = pd.crosstab(d['a'],d['b'])
```
gives a Cramer's V of 0.708333333333, while they have the exact same information (and dummy encoding).

**Comment by dpavlic** [comment]
The issue directly above is due to the small counts, where the chi-squared test is going to give us a potentially incorrect approximation. The problem disappears in the above example if we use Monte Carlo simulation to boost our sample. Please excuse the context switch to R, but it seems to me that the Monte Carlo simulation option is not implemented in scipy:

```
# Let's compute the chi-sq test.
chisq.test(chiTable)
# Returns:
# X-squared = 3.5122, df = 1, p-value = 0.06092
# Warning message:
# In chisq.test(chiTable) : Chi-squared approximation may be incorrect

# Now let us try with Monte Carlo simulation.
chisq.test(chiTable, simulate.p.value = TRUE)
# Returns:
# X-squared = 7, df = NA, p-value = 0.02699
```
So, using the above, let's try Cramer'sV (R package lsr):

```
# Cramer's V, without Monte Carlo
cramersV(chiTable)
# Returns:
# 0.7083333 (same as Jos)

# Cramer's V, Monte Carlo
cramersV(chiTable, simulate.p.value = TRUE)
# Returns:
# 1
```

**Comment by JosPolfliet** [comment]
Most people probably have larger tables than 7 rows, so I propose we use it as is for now without the Monte Carlo correction for small sample sizes. I think an implementation of the latter would belong in scipy.stats, and not in pandas-profiling.

**Comment by tejaslodaya** [comment]
I found out why it was giving 0.708 for perfectly correlated variables. That's because of Yates's continuity correction, which is the default.

Yate's correction subtracts 0.5 from the difference between each observed value and its expected value in a 2 × 2 contingency table

The effect of Yates' correction is to prevent overestimation of statistical significance for small data. It is chiefly used when at least one cell of the table has an expected count smaller than 5. **Unfortunately, Yates' correction may tend to overcorrect. This can result in an overly conservative result that fails to reject the null hypothesis when it should (a type II error). So it is suggested that Yates' correction is unnecessary even with quite low sample sizes**

If we change the chi2_contingency parameters, we achieve correct results
```
def cramers_corrected_stat(confusion_matrix):
    chi2 = stats.chi2_contingency(confusion_matrix,correction=False)[0]
    n = confusion_matrix.sum().sum()
    phi2 = chi2/n
    r,k = confusion_matrix.shape
    phi2corr = max(0, phi2 - ((k-1)*(r-1))/(n-1))
    rcorr = r - ((r-1)**2)/(n-1)
    kcorr = k - ((k-1)**2)/(n-1)
    return np.sqrt(phi2corr / min( (kcorr-1), (rcorr-1)))

d=pd.DataFrame(index=range(1,8))
d['a'] = ['chien', 'chien', 'chien', 'chien', 'chat','chat','chat']
d['b'] = ['dog', 'dog', 'dog', 'dog', 'cat','cat','cat']
ct = pd.crosstab(d['a'],d['b'])

cramers_corrected_stat(ct)
#Returns 1.0
```


Ref :
1) [Wikipedia](https://en.wikipedia.org/wiki/Yates's_correction_for_continuity)
2) [Scipy](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.chi2_contingency.html)

**Comment by conradoqg** [comment]
Hey

I'm going to implement this on v1.5.

In resume:
- Categories should use the Cramers V;
- Everything else the default pandas correlation matrix;

Am I correct?

Best

**Comment by rmokros** [comment]
Hi, if there is any work on this topic if you like I have a bunch o test sets an can help with the testing ….
