### ISSUE TITLE
MAD is "Median Absolute Deviation" or "mean absolute deviation" ?

### ISSUE THREAD

**Issue by jiangfangfangxm** [pandas-profiling/pandas-profiling#453]
**Describe the bug**
I found the Descriptive statistics for variables in the report  has one item:
        Median Absolute Deviation(MAD)"
but in the code, model:  describe.py line 67:
         "mad": series.mad(),
In pandas 1.01: Series.mad is to caculate "the mean absolute deviation of the values"
   Series.mad(self, axis=None, skipna=None, level=None)[source]¶
   Return the mean absolute deviation of the values for the requested axis.
So, I guess the descriptive statistics should be "Mean Absolute Deviation(MAD)"

![image](https://user-images.githubusercontent.com/45526589/80865935-d6953900-8cbe-11ea-87b1-2f3bfc01e51c.png)
![pic2](https://user-images.githubusercontent.com/45526589/80866054-3ee41a80-8cbf-11ea-9672-817747a639a1.jpg)
![image](https://user-images.githubusercontent.com/45526589/80866091-7e126b80-8cbf-11ea-96ce-241d42223f28.png)

**To Reproduce**

 

**Version information:**

**Additional context**

**Comment by loopyme** [comment]
This is indeed a bug. At v2.6.0, the calculation is wrong, it will get 'mean absolute deviation' while we actually want 'median absolute deviation'.

As far as I know, it has been fixed by @sbrugman in the develop branch (See [describe.py](https://github.com/pandas-profiling/pandas-profiling/blob/develop/src/pandas_profiling/model/describe.py) line 56) and will be fixed in the next release.

**Comment by sbrugman** [comment]
Great catch. This is fixed in the development branch and will be in the next release.
