### ISSUE TITLE
Pandas Profiling KeyError

### ISSUE THREAD

**Issue by anhailing** [pandas-profiling/pandas-profiling#498]
**Describe the bug**
When running below code, running into error KeyError: 'Requested level (var1) does not match index name (None)'. I created a new environment with only python=3.7.7, jupyterlab=2.1.4, pandas-profiling=2.8.0.  However the pip freeze reported pandas-profilling==2.3.0.  I used conda install -c conda-forge pandas-profiling.

**To Reproduce**

 

**Version information:**

**Additional context**

**Comment by josefinwinberg** [comment]
I experience the same.

**Comment by sbrugman** [comment]
Thanks for reporting this issue. We've seen variations on this issue before. There are various things that can cause an older version the be executed, resulting in these kind of errors. One source of error is when pip and conda packages are installed in the same environment (https://github.com/conda-forge/pandas-profiling-feedstock/issues/22). This might also be the case here, as you report installing with conda and checking versions with `pip freeze` instead of `conda list` and `conda info`. Several ways to troubleshoot are:
- Install a completely fresh environment (which @anhailing already did)
- Check each step and report the results.

I'd be more than willing to create a dedicated page in the docs for resolving this issue for new users, as we've seen variations before. Please let us know.

**Comment by anhailing** [comment]
Below are the installation commands I used. 
conda create --name test python=3.7 
conda install -c conda-forge pandas-profiling
conda install -c conda-forge jupyterlab

conda list reports pandas-profiling=2.8.0

@sbrugman Can you provide a step by step instruction to make the minimal environment work?

**Comment by sbrugman** [comment]
Assuming you're in a notebook, one thing that can cause problems is that your jupyter picks another interpreter than that of the environment.

- Location of the env's interpreter: `conda activate [env]
which python`
- Within the notebook: `!which python`

**Comment by anhailing** [comment]
I reinstalled miniconda on my laptop and only set up one environment to test this.  The same error existed.  I did the exact same thing on a windows server, it worked.  Any other thoughts? @sbrugman

**Comment by anhailing** [comment]
I figured it out.  I pip installed a package xxx which used pandas-profiling=2.3.0 as prerequisite.  I never pip uninstalled the package before I removed the environment. Somehow, it messed the pandas-profiling installation.  However, pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip still worked.   After I pip uninstalled this package,  both conda install and regular pip install worked.
