### ISSUE TITLE
Numeric with low Distinct count should be treated as "Categorical"

### ISSUE THREAD

**Issue by eamag** [pandas-profiling/pandas-profiling#72]
I guess <15 is ok, because mean, min, max and zeros are kind of useless

**Comment by navado** [comment]
I'd say it should be parameter

**Comment by romainx** [comment]
It's a good suggestion. We could define a threshold of distinct values. Below this threshold the variable will be treated as categorical since it can make more sense from an analysis perspective.
However you can obtain the expected result right now by converting the variable you want to see as categorical before performing the call to `pandas_profiling`.

```python
df = pd.DataFrame({"A":[1,2,3,3]})
df["B"] = df["A"].apply(str)
pandas_profiling.ProfileReport(df)
```
<img width="835" alt="categ" src="https://user-images.githubusercontent.com/7131913/33804111-67c6130e-dd9e-11e7-994a-7da12c9ca755.png">

**Comment by jankaWIS** [comment]
Hi, I'd have a question about this. What if I do not want to treat a numerical variable as a categorical but yet it does not have more than 15 unique values, how can I achieve that? Because now it treats it as categorical. Thanks

**Comment by sbrugman** [comment]
You can control when PP treats a numerical variable as categorical. To completely disable, set `vars.num.low_categorical_threshold` to zero.

Details [here](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/advanced_usage.html#variable-summary-settings).
