### ISSUE TITLE
Add "target" variable to ProfileReport and then add more graphs

### ISSUE THREAD

**Issue by eamag** [pandas-profiling/pandas-profiling#73]
https://seaborn.pydata.org/generated/seaborn.countplot.html is very useful if target is categorical. so it'd be nice to plot it if necessary

**Comment by Aylr** [comment]
How is this better than what's already there? If the column is categorical you'll get that histogram.

**Comment by eamag** [comment]
countplot and histogram are different things, we may see different distributions in countplot

**Comment by conradoqg** [comment]
I think what @eamag meant is that with a countplot you can compare side-by-side the distribution of different categorical fields, where the Y is the count. See [https://seaborn.pydata.org/tutorial/categorical.html](https://seaborn.pydata.org/tutorial/categorical.html)

One way to implement this feature is to generate a countplot on each categorical field against every other one. I'm sure this will hurt the performance and won't give meaningful value to the user.

In an exploratory process, usually, you need to choose rationally which categorical fields you want to compare (like the Titanic example in the above link).

Creating plots by comparing all categorical fields, like A vs B, B vs C, C vs A (2-fields) or A vs B vs C (3-fields) will create an exponential amount of plots (because it is a combinatory analysis).

In my opinion, we shouldn't implement this feature.

Best

**Comment by romainx** [comment]
Hello,

I still keep it open it could be studied.

**Comment by bensdm** [comment]
I agree this would be a great feature

> I think what @eamag meant is that with a countplot you can compare side-by-side the distribution of different categorical fields, where the Y is the count. See https://seaborn.pydata.org/tutorial/categorical.html
> 
> One way to implement this feature is to generate a countplot on each categorical field against every other one. I'm sure this will hurt the performance and won't give meaningful value to the user.
> 
> In an exploratory process, usually, you need to choose rationally which categorical fields you want to compare (like the Titanic example in the above link).
> 
> Creating plots by comparing all categorical fields, like A vs B, B vs C, C vs A (2-fields) or A vs B vs C (3-fields) will create an exponential amount of plots (because it is a combinatory analysis).
> 
> In my opinion, we shouldn't implement this feature.
> 
> Best

I do not understand your point, is it really heavier to plot 
![image](https://user-images.githubusercontent.com/29406515/61830502-e8dd6f00-ae30-11e9-9589-567a770162a8.png)

instead of plotting ?

![image](https://user-images.githubusercontent.com/29406515/61830634-3f4aad80-ae31-11e9-87c8-de866e14e556.png)
